# Generated by Django 5.1 on 2024-09-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingCar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NumeroPlace', models.IntegerField()),
                ('PlaceCodeQr', models.CharField(max_length=500)),
                ('MatriculeCar', models.CharField(max_length=500)),
                ('DateCreate', models.DateField()),
                ('TypeMouvement', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('PlaceId', models.AutoField(primary_key=True, serialize=False)),
                ('PlaceNumero', models.IntegerField()),
                ('PlaceCodeQr', models.CharField(max_length=500)),
                ('DateCreatePlace', models.DateField()),
                ('Reserver', models.BooleanField()),
                ('MatriculeCar', models.CharField(default='no car', max_length=500)),
            ],
        ),
    ]
