# Generated by Django 5.1 on 2024-09-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingCar', '0002_history_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='Reserver',
            field=models.BooleanField(default=False),
        ),
    ]
