# Generated by Django 5.1 on 2024-09-09 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingCar', '0003_alter_places_reserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='DateEdit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
