# Generated by Django 5.1.1 on 2024-09-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingCar', '0005_alter_history_placecodeqr_alter_places_placecodeqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='PhotoFileName',
            field=models.CharField(default='Anonymous.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='places',
            name='MatriculeCar',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
