# Generated by Django 5.1.1 on 2024-09-10 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingCar', '0006_places_photofilename_alter_places_matriculecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='places',
            name='Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
